import Foundation

// Português (Brasil) — only pt-BR, no pt-PT.
let stringsPtBR: [String: String] = [
    "tagline": "Esqueça os comandos, vá direto ao trabalho.",
    "drop.title": "Solte a pasta do seu projeto aqui",
    "drop.subtitle": "Sem precisar decorar comandos, eu descubro",
    "drop.button": "Escolher pasta",
    "drop.doodle": "drag it!",
    "drop.hover.title": "drop it here",
    "drop.hover.subtitle": "Peguei!",
    "drop.hover.doodle": "gimme!",
    "drop.lastLaunched": "Última execução: ",
    "launch.title": "Analisando o projeto",
    "launch.subtitle": "Vamos ver o que tem nessa pasta",
    "launch.doodle": "digging⋯",
    "launch.cancel": "Deixa pra lá",
    "empty.title": "Nada rodando no momento",
    "empty.zzz": "zzz⋯",
    "autoclose.title": "Fechamento automático",
    "autoclose.subtitle": "Projetos ociosos serão fechados automaticamente",
    "running.title": "Projetos em execução",
    "running.killAll": "Parar tudo",
    "running.refresh": "Atualizar",
    "settings.title": "Ajustes",
    "settings.general": "Geral",
    "settings.about": "Sobre",
    "settings.story": "História",
    "story.heading": "Por que eu fiz esse app",
    "story.p1": "Eu não sou desenvolvedor profissional. Depois de muito vibe coding, fui acumulando cada vez mais projetos, não conseguia lembrar os comandos de inicialização e nem sabia mais quais portas do localhost ainda estavam rodando.",
    "story.p2": "E eu não queria ter que perguntar pra uma IA de novo só para colocar um projeto pra rodar.",
    "story.p3": "Então eu criei o mole. É só soltar a pasta que ele cuida do resto.",
    "story.closing": "Esqueça os comandos, vá direto ao trabalho.",
    "settings.language": "Idioma",
    "settings.github": "Ver no GitHub",
    "settings.license": "Licença MIT",
    "settings.reportIssue": "Reportar um problema",
    "alert.stop.confirm": "Parar",
    "alert.cancel": "Cancelar",
    "alert.stopTitle": "Parar localhost:%@?",
    "alert.killAllTitle": "Parar tudo?",
    "alert.killAllMessage": "Isso vai parar %d servidor(es) de desenvolvimento (localhost:%@).",
    "alert.killAllSkipped": "\n%d serviço(s) marcados como \"Manter ativo\" não serão parados.",
    "pin.tooltip": "Manter ativo: não será fechado automaticamente",
    "project.pinned": "fixado",
    "project.running": "Em execução",
    "project.stop": "Parar",
    "project.keepAlive": "Manter ativo",
    "common.choose": "Escolher",
    "expire.30m": "30 min",
    "expire.1h": "1 hora",
    "expire.2h": "2 horas (padrão)",
    "expire.4h": "4 horas",
    "expire.never": "Nunca",
    "launch.detecting": "Detectando o tipo de projeto…",
    "launch.waitingServer": "Iniciado em segundo plano, aguardando ficar pronto…",
    "launch.opened": " (aberto)",
    "launch.noPortNotice": "Iniciado, mas nenhuma porta web nova foi detectada (pode ser um app nativo ou um serviço de backend/banco de dados sem página web — isso é esperado. Se ainda estiver esperando o Docker, confira o log em vez de soltar a pasta de novo)",
    "launch.waitingElapsed": "Aguardando o localhost… (%d s até agora, você pode conferir o log a qualquer momento)",
    "launch.elapsedSuffix": " (%d s até agora)",
    "autoclose.notice": "localhost:%@ fechado automaticamente (rodando há mais de %d minutos)",
    "update.downloading": "Baixando atualização…",
    "update.downloadFailed": "Falha no download",
    "update.downloadFailedWithError": "Falha ao baixar a atualização: %@",
    "update.installing": "Instalando…",
    "update.mountFailed": "Falha ao montar a imagem de atualização",
    "update.appNotFoundInImage": "Não foi possível encontrar o mole.app dentro da imagem de atualização",
    "update.replacing": "Substituindo a versão antiga…",
    "update.copyFailed": "Falha ao copiar a nova versão: %@",
    "update.installFailed": "Falha ao instalar a nova versão (pode ser um problema de permissão) — baixe manualmente na página de Releases: %@",
    "update.restarting": "Atualização concluída, reiniciando…",
    "update.updating": "Atualizando…",
    "update.newVersionAvailable": "🎉 Uma nova versão (v%@) está disponível",
    "update.now": "Atualizar agora",
    "update.viewRelease": "Ver versão",
    "loading.detecting": "Detectando o projeto…",
    "loading.preparing": "Preparando o ambiente…",
    "loading.startingServer": "Iniciando o servidor de desenvolvimento…",
    "loading.waitingLocalhost": "Aguardando o localhost…",
    "loading.openingBrowser": "Abrindo o navegador…",
    "loading.ready": "O projeto está pronto.",
    "error.projectNotFound": "Projeto não encontrado.",
    "error.folderInaccessible": "Não foi possível acessar essa pasta.",
    "error.portInUse": "Essa porta já está em uso.",
    "error.commandFailed": "O comando falhou ao executar.",
    "error.unableToStartServer": "Não foi possível iniciar o servidor.",
    "error.dependencyMissing": "Uma dependência necessária está faltando.",
    "error.invalidProject": "Isso não parece ser um projeto válido.",
    "error.permissionDenied": "Permissão negada.",
    "error.browserFailedToOpen": "Não foi possível abrir o navegador.",
    "error.processStoppedUnexpectedly": "O processo parou inesperadamente.",
    "uptime.days": "Rodando há %d dia(s) %d h",
    "uptime.hours": "Rodando há %d h %d min",
    "uptime.minutes": "Rodando há %d min",
    "uptime.seconds": "Rodando há %d s",
    "uptime.short.days": "%dd",
    "uptime.short.hours": "%dh",
    "uptime.short.minutes": "%dmin",
    "uptime.short.lessThanMinute": "< 1 min",
    "about.credit": "Feito por Wen e Claude, juntos ⌯^⦁𖥦⦁^⌯",
]
