import Foundation

// Deutsch (German)
let stringsDE: [String: String] = [
    "tagline": "Keine Befehle, einfach loslegen.",
    "drop.title": "Projektordner hier ablegen",
    "drop.subtitle": "Keine Befehle merken, ich kümmere mich darum",
    "drop.button": "Ordner wählen",
    "drop.doodle": "drag it!",
    "drop.hover.title": "drop it here",
    "drop.hover.subtitle": "Hab ihn!",
    "drop.hover.doodle": "gimme!",
    "drop.lastLaunched": "Zuletzt gestartet: ",
    "launch.title": "Projekt wird analysiert",
    "launch.subtitle": "Mal sehen, was in diesem Ordner steckt",
    "launch.doodle": "digging⋯",
    "launch.cancel": "Doch nicht",
    "empty.title": "Gerade läuft nichts",
    "empty.zzz": "zzz⋯",
    "autoclose.title": "Automatisches Schließen",
    "autoclose.subtitle": "Inaktive Projekte werden automatisch geschlossen",
    "running.title": "Laufende Projekte",
    "running.killAll": "Alle stoppen",
    "running.refresh": "Aktualisieren",
    "settings.title": "Einstellungen",
    "settings.general": "Allgemein",
    "settings.about": "Info",
    "settings.story": "Geschichte",
    "story.heading": "Warum ich diese App gemacht habe",
    "story.p1": "Ich bin kein professioneller Entwickler. Nach viel Vibe Coding hatte ich immer mehr Projekte, konnte mir die Start-Befehle nicht merken und wusste oft nicht mehr, welche localhost-Ports überhaupt noch liefen.",
    "story.p2": "Und ich wollte nicht jedes Mal eine KI fragen müssen, nur um ein Projekt wieder zu starten.",
    "story.p3": "Also habe ich mole gebaut. Ordner reinziehen, den Rest erledigt es von selbst.",
    "story.closing": "Keine Befehle, einfach loslegen.",
    "settings.language": "Sprache",
    "settings.github": "Auf GitHub ansehen",
    "settings.license": "MIT-Lizenz",
    "settings.reportIssue": "Problem melden",
    "alert.stop.confirm": "Stoppen",
    "alert.cancel": "Abbrechen",
    "alert.stopTitle": "localhost:%@ stoppen?",
    "alert.killAllTitle": "Alle stoppen?",
    "alert.killAllMessage": "Dadurch werden %d Dev-Server (localhost:%@) gestoppt.",
    "alert.killAllSkipped": "\n%d als „Dauerhaft aktiv“ markierte Dienste werden nicht gestoppt.",
    "pin.tooltip": "Dauerhaft aktiv: wird nicht automatisch geschlossen",
    "project.pinned": "angeheftet",
    "project.running": "Läuft",
    "project.stop": "Stoppen",
    "project.keepAlive": "Dauerhaft aktiv",
    "common.choose": "Wählen",
    "expire.30m": "30 Min.",
    "expire.1h": "1 Stunde",
    "expire.2h": "2 Stunden (Standard)",
    "expire.4h": "4 Stunden",
    "expire.never": "Nie",
    "launch.detecting": "Projekttyp wird erkannt…",
    "launch.waitingServer": "Im Hintergrund gestartet, warte auf Bereitschaft…",
    "launch.opened": " (geöffnet)",
    "launch.noPortNotice": "Gestartet, aber kein neuer Web-Port erkannt (das kann eine native App oder ein Backend-/Datenbankdienst ohne Webseite sein — das ist normal. Falls noch auf Docker gewartet wird, im Log statt erneutem Ablegen nachsehen)",
    "launch.waitingElapsed": "Warte auf localhost… (%d Sek. vergangen, das Log kann jederzeit eingesehen werden)",
    "launch.elapsedSuffix": " (%d Sek. vergangen)",
    "autoclose.notice": "localhost:%@ automatisch geschlossen (lief länger als %d Minuten)",
    "update.downloading": "Update wird heruntergeladen…",
    "update.downloadFailed": "Download fehlgeschlagen",
    "update.downloadFailedWithError": "Update-Download fehlgeschlagen: %@",
    "update.installing": "Wird installiert…",
    "update.mountFailed": "Update-Image konnte nicht eingebunden werden",
    "update.appNotFoundInImage": "mole.app wurde im Update-Image nicht gefunden",
    "update.replacing": "Alte Version wird ersetzt…",
    "update.copyFailed": "Neue Version konnte nicht kopiert werden: %@",
    "update.installFailed": "Neue Version konnte nicht installiert werden (evtl. Berechtigungsproblem) — bitte manuell über die Releases-Seite herunterladen: %@",
    "update.restarting": "Update abgeschlossen, wird neu gestartet…",
    "update.updating": "Wird aktualisiert…",
    "update.newVersionAvailable": "🎉 Eine neue Version (v%@) ist verfügbar",
    "update.now": "Jetzt aktualisieren",
    "update.viewRelease": "Release ansehen",
    "loading.detecting": "Projekt wird erkannt…",
    "loading.preparing": "Umgebung wird vorbereitet…",
    "loading.startingServer": "Entwicklungsserver wird gestartet…",
    "loading.waitingLocalhost": "Warte auf localhost…",
    "loading.openingBrowser": "Browser wird geöffnet…",
    "loading.ready": "Projekt ist bereit.",
    "error.projectNotFound": "Projekt nicht gefunden.",
    "error.folderInaccessible": "Auf diesen Ordner kann nicht zugegriffen werden.",
    "error.portInUse": "Dieser Port wird bereits verwendet.",
    "error.commandFailed": "Der Befehl konnte nicht ausgeführt werden.",
    "error.unableToStartServer": "Der Server konnte nicht gestartet werden.",
    "error.dependencyMissing": "Eine erforderliche Abhängigkeit fehlt.",
    "error.invalidProject": "Das sieht nicht wie ein gültiges Projekt aus.",
    "error.permissionDenied": "Zugriff verweigert.",
    "error.browserFailedToOpen": "Der Browser konnte nicht geöffnet werden.",
    "error.processStoppedUnexpectedly": "Der Prozess wurde unerwartet beendet.",
    "uptime.days": "Läuft seit %d Tag(en) %d Std.",
    "uptime.hours": "Läuft seit %d Std. %d Min.",
    "uptime.minutes": "Läuft seit %d Min.",
    "uptime.seconds": "Läuft seit %d Sek.",
    "uptime.short.days": "%dT",
    "uptime.short.hours": "%dStd",
    "uptime.short.minutes": "%dMin",
    "uptime.short.lessThanMinute": "< 1 Min.",
    "about.credit": "Gemeinsam gemacht von Wen und Claude ⌯^⦁𖥦⦁^⌯",
]
