import Foundation

// 한국어 (Korean)
let stringsKO: [String: String] = [
    "tagline": "명령어는 잊고, 바로 시작하세요",
    "drop.title": "프로젝트 폴더를 여기로 드래그하세요",
    "drop.subtitle": "명령어를 몰라도 괜찮아요, 제가 알아서 할게요",
    "drop.button": "폴더 선택",
    "drop.doodle": "drag it!",
    "drop.hover.title": "drop it here",
    "drop.hover.subtitle": "받았어요!",
    "drop.hover.doodle": "gimme!",
    "drop.lastLaunched": "마지막 실행: ",
    "launch.title": "프로젝트 분석 중",
    "launch.subtitle": "이 폴더 안에 뭐가 있는지 살펴볼게요",
    "launch.doodle": "digging⋯",
    "launch.cancel": "취소할게요",
    "empty.title": "지금 실행 중인 프로젝트가 없어요",
    "empty.zzz": "zzz⋯",
    "autoclose.title": "자동 종료",
    "autoclose.subtitle": "유휴 상태인 프로젝트는 자동으로 종료돼요",
    "running.title": "실행 중인 프로젝트",
    "running.killAll": "모두 종료",
    "running.refresh": "새로고침",
    "settings.title": "설정",
    "settings.general": "일반",
    "settings.about": "정보",
    "settings.story": "이야기",
    "story.heading": "이 앱을 만든 이유",
    "story.p1": "저는 전문 개발자가 아니에요. 바이브 코딩을 계속하다 보니 프로젝트가 점점 늘어났고, 실행 명령어를 다 외우지 못했고, 어떤 localhost 포트가 켜져 있는지도 헷갈리기 시작했어요.",
    "story.p2": "그렇다고 프로젝트를 다시 실행하려고 매번 AI에게 다시 물어보고 싶지도 않았어요.",
    "story.p3": "그래서 mole을 만들었어요. 폴더만 넣으면 나머지는 알아서 처리해요.",
    "story.closing": "명령어는 잊고, 바로 시작하세요.",
    "settings.language": "언어",
    "settings.github": "GitHub에서 보기",
    "settings.license": "MIT 라이선스",
    "settings.reportIssue": "문제 신고",
    "alert.stop.confirm": "종료",
    "alert.cancel": "취소",
    "alert.stopTitle": "localhost:%@ 를 종료할까요?",
    "alert.killAllTitle": "모두 종료할까요?",
    "alert.killAllMessage": "%d 개의 개발 서버(localhost:%@)를 종료해요.",
    "alert.killAllSkipped": "\n'항상 유지'로 표시된 %d 개의 서비스는 종료되지 않아요.",
    "pin.tooltip": "항상 유지: 자동 종료되지 않아요",
    "project.pinned": "고정됨",
    "project.running": "실행 중",
    "project.stop": "종료",
    "project.keepAlive": "항상 유지",
    "common.choose": "선택",
    "expire.30m": "30분",
    "expire.1h": "1시간",
    "expire.2h": "2시간(기본값)",
    "expire.4h": "4시간",
    "expire.never": "자동 종료 안 함",
    "launch.detecting": "프로젝트 종류 확인 중…",
    "launch.waitingServer": "백그라운드에서 실행했어요. 준비될 때까지 기다리는 중…",
    "launch.opened": " (열림)",
    "launch.noPortNotice": "실행은 됐지만 새로운 웹 포트가 감지되지 않았어요 (네이티브 앱이거나 웹 페이지가 없는 백엔드/데이터베이스 서비스라면 정상이에요. Docker를 기다리는 중이라면 다시 드래그하지 말고 로그에서 진행 상황을 확인하세요)",
    "launch.waitingElapsed": "localhost를 기다리는 중…(%d초 경과, 언제든 로그를 확인할 수 있어요)",
    "launch.elapsedSuffix": " (%d초 경과)",
    "autoclose.notice": "localhost:%@ 를 자동으로 종료했어요 (%d분 넘게 실행 중이었어요)",
    "update.downloading": "업데이트 다운로드 중…",
    "update.downloadFailed": "다운로드 실패",
    "update.downloadFailedWithError": "업데이트 다운로드 실패: %@",
    "update.installing": "설치 중…",
    "update.mountFailed": "업데이트 이미지 마운트 실패",
    "update.appNotFoundInImage": "업데이트 이미지에서 mole.app을 찾을 수 없어요",
    "update.replacing": "이전 버전을 교체하는 중…",
    "update.copyFailed": "새 버전 복사 실패: %@",
    "update.installFailed": "새 버전 설치에 실패했어요 (권한 문제일 수 있어요). Release 페이지에서 직접 다운로드해 주세요: %@",
    "update.restarting": "업데이트 완료, 재시작하는 중…",
    "update.updating": "업데이트 중…",
    "update.newVersionAvailable": "🎉 새 버전 v%@ 을 사용할 수 있어요",
    "update.now": "지금 업데이트",
    "update.viewRelease": "릴리스 보기",
    "loading.detecting": "프로젝트 감지 중…",
    "loading.preparing": "환경 준비 중…",
    "loading.startingServer": "개발 서버 시작 중…",
    "loading.waitingLocalhost": "localhost를 기다리는 중…",
    "loading.openingBrowser": "브라우저 여는 중…",
    "loading.ready": "프로젝트 준비 완료.",
    "error.projectNotFound": "프로젝트를 찾을 수 없어요.",
    "error.folderInaccessible": "이 폴더에 접근할 수 없어요.",
    "error.portInUse": "이 포트는 이미 사용 중이에요.",
    "error.commandFailed": "명령 실행에 실패했어요.",
    "error.unableToStartServer": "서버를 시작할 수 없었어요.",
    "error.dependencyMissing": "필요한 의존성이 없어요.",
    "error.invalidProject": "유효한 프로젝트가 아닌 것 같아요.",
    "error.permissionDenied": "권한이 없어요.",
    "error.browserFailedToOpen": "브라우저를 열 수 없었어요.",
    "error.processStoppedUnexpectedly": "프로세스가 예기치 않게 중단됐어요.",
    "uptime.days": "%d일 %d시간째 실행 중",
    "uptime.hours": "%d시간 %d분째 실행 중",
    "uptime.minutes": "%d분째 실행 중",
    "uptime.seconds": "%d초째 실행 중",
    "uptime.short.days": "%d일",
    "uptime.short.hours": "%d시간",
    "uptime.short.minutes": "%d분",
    "uptime.short.lessThanMinute": "< 1분",
    "about.credit": "Wen과 Claude가 함께 만들었어요 ⌯^⦁𖥦⦁^⌯",
]
