import Foundation

// Français (French)
let stringsFR: [String: String] = [
    "tagline": "Oubliez les commandes, passez au travail.",
    "drop.title": "Déposez votre dossier de projet ici",
    "drop.subtitle": "Pas besoin de retenir les commandes, je m'en occupe",
    "drop.button": "Choisir un dossier",
    "drop.doodle": "drag it!",
    "drop.hover.title": "drop it here",
    "drop.hover.subtitle": "Je l'ai !",
    "drop.hover.doodle": "gimme!",
    "drop.lastLaunched": "Dernier lancement : ",
    "launch.title": "Analyse du projet",
    "launch.subtitle": "Voyons ce que contient ce dossier",
    "launch.doodle": "digging⋯",
    "launch.cancel": "Laisser tomber",
    "empty.title": "Rien ne tourne pour le moment",
    "empty.zzz": "zzz⋯",
    "autoclose.title": "Fermeture automatique",
    "autoclose.subtitle": "Les projets inactifs se ferment automatiquement",
    "running.title": "Projets en cours",
    "running.killAll": "Tout arrêter",
    "running.refresh": "Actualiser",
    "settings.title": "Réglages",
    "settings.general": "Général",
    "settings.about": "À propos",
    "settings.story": "Histoire",
    "story.heading": "Pourquoi j'ai créé cette app",
    "story.p1": "Je ne suis pas développeur de métier. À force de vibe coding, j'ai accumulé de plus en plus de projets, sans jamais retenir les commandes de lancement, et je perdais même le fil des ports localhost encore actifs.",
    "story.p2": "Et je n'avais pas envie de redemander à une IA juste pour relancer un projet.",
    "story.p3": "Alors j'ai créé mole. On dépose le dossier, et il s'occupe du reste.",
    "story.closing": "Oubliez les commandes, passez au travail.",
    "settings.language": "Langue",
    "settings.github": "Voir sur GitHub",
    "settings.license": "Licence MIT",
    "settings.reportIssue": "Signaler un problème",
    "alert.stop.confirm": "Arrêter",
    "alert.cancel": "Annuler",
    "alert.stopTitle": "Arrêter localhost:%@ ?",
    "alert.killAllTitle": "Tout arrêter ?",
    "alert.killAllMessage": "Cela arrêtera %d serveur(s) de développement (localhost:%@).",
    "alert.killAllSkipped": "\n%d service(s) marqué(s) « Toujours actif » ne seront pas arrêtés.",
    "pin.tooltip": "Toujours actif : ne sera pas fermé automatiquement",
    "project.pinned": "épinglé",
    "project.running": "Actif",
    "project.stop": "Arrêter",
    "project.keepAlive": "Toujours actif",
    "common.choose": "Choisir",
    "expire.30m": "30 min",
    "expire.1h": "1 heure",
    "expire.2h": "2 heures (par défaut)",
    "expire.4h": "4 heures",
    "expire.never": "Jamais",
    "launch.detecting": "Détection du type de projet…",
    "launch.waitingServer": "Lancé en arrière-plan, en attente de démarrage…",
    "launch.opened": " (ouvert)",
    "launch.noPortNotice": "Lancé, mais aucun nouveau port web détecté (il peut s'agir d'une app native ou d'un service backend/base de données sans page web — c'est normal. Si Docker est encore en train de démarrer, consultez le journal plutôt que de redéposer le dossier)",
    "launch.waitingElapsed": "En attente de localhost… (%d s écoulées, vous pouvez consulter le journal à tout moment)",
    "launch.elapsedSuffix": " (%d s écoulées)",
    "autoclose.notice": "localhost:%@ fermé automatiquement (actif depuis plus de %d minutes)",
    "update.downloading": "Téléchargement de la mise à jour…",
    "update.downloadFailed": "Échec du téléchargement",
    "update.downloadFailedWithError": "Échec du téléchargement de la mise à jour : %@",
    "update.installing": "Installation…",
    "update.mountFailed": "Échec du montage de l'image de mise à jour",
    "update.appNotFoundInImage": "Impossible de trouver mole.app dans l'image de mise à jour",
    "update.replacing": "Remplacement de l'ancienne version…",
    "update.copyFailed": "Échec de la copie de la nouvelle version : %@",
    "update.installFailed": "Échec de l'installation de la nouvelle version (problème de permissions possible) — téléchargez-la manuellement depuis la page Releases : %@",
    "update.restarting": "Mise à jour terminée, redémarrage…",
    "update.updating": "Mise à jour…",
    "update.newVersionAvailable": "🎉 Une nouvelle version (v%@) est disponible",
    "update.now": "Mettre à jour",
    "update.viewRelease": "Voir la version",
    "loading.detecting": "Détection du projet…",
    "loading.preparing": "Préparation de l'environnement…",
    "loading.startingServer": "Démarrage du serveur de développement…",
    "loading.waitingLocalhost": "En attente de localhost…",
    "loading.openingBrowser": "Ouverture du navigateur…",
    "loading.ready": "Le projet est prêt.",
    "error.projectNotFound": "Projet introuvable.",
    "error.folderInaccessible": "Impossible d'accéder à ce dossier.",
    "error.portInUse": "Ce port est déjà utilisé.",
    "error.commandFailed": "La commande a échoué.",
    "error.unableToStartServer": "Impossible de démarrer le serveur.",
    "error.dependencyMissing": "Une dépendance requise est manquante.",
    "error.invalidProject": "Ce dossier ne ressemble pas à un projet valide.",
    "error.permissionDenied": "Permission refusée.",
    "error.browserFailedToOpen": "Impossible d'ouvrir le navigateur.",
    "error.processStoppedUnexpectedly": "Le processus s'est arrêté de façon inattendue.",
    "uptime.days": "Actif depuis %d j %d h",
    "uptime.hours": "Actif depuis %d h %d min",
    "uptime.minutes": "Actif depuis %d min",
    "uptime.seconds": "Actif depuis %d s",
    "uptime.short.days": "%dj",
    "uptime.short.hours": "%dh",
    "uptime.short.minutes": "%dmin",
    "uptime.short.lessThanMinute": "< 1 min",
    "about.credit": "Créé par Wen et Claude, ensemble ⌯^⦁𖥦⦁^⌯",
]
