import Foundation

// 简体中文 (Simplified Chinese)
let stringsZhCN: [String: String] = [
    "tagline": "别管指令，直接开工",
    "drop.title": "把项目文件夹拖到这里",
    "drop.subtitle": "不用记指令，我来判断",
    "drop.button": "选择文件夹",
    "drop.doodle": "drag it!",
    "drop.hover.title": "drop it here",
    "drop.hover.subtitle": "我接住了！",
    "drop.hover.doodle": "gimme!",
    "drop.lastLaunched": "上次启动：",
    "launch.title": "正在分析项目",
    "launch.subtitle": "看看这个文件夹里藏了什么",
    "launch.doodle": "digging⋯",
    "launch.cancel": "先不等了",
    "empty.title": "目前没有项目在跑",
    "empty.zzz": "zzz⋯",
    "autoclose.title": "自动关闭",
    "autoclose.subtitle": "闲置项目将自动关闭",
    "running.title": "运行中的项目",
    "running.killAll": "全部关闭",
    "running.refresh": "刷新",
    "settings.title": "设置",
    "settings.general": "通用",
    "settings.about": "关于",
    "settings.story": "故事",
    "story.heading": "为什么做这个 App？",
    "story.p1": "我不是专业开发者。Vibe coding 做久了，项目越来越多，启动指令记不住，连 localhost 开了哪些也常常搞不清楚。",
    "story.p2": "我又不想每次只是为了重新把项目跑起来，就再问一次 AI。",
    "story.p3": "所以做了 mole。把文件夹丢进来，剩下交给它。",
    "story.closing": "别管指令，直接开工。",
    "settings.language": "语言",
    "settings.github": "在 GitHub 上查看",
    "settings.license": "MIT 授权",
    "settings.reportIssue": "反馈问题",
    "alert.stop.confirm": "关闭",
    "alert.cancel": "取消",
    "alert.stopTitle": "关闭 localhost:%@？",
    "alert.killAllTitle": "全部关闭？",
    "alert.killAllMessage": "会关闭 %d 个开发服务器（localhost:%@)。",
    "alert.killAllSkipped": "\n标记为「常驻」的 %d 个服务不会被关闭。",
    "pin.tooltip": "常驻：不会被自动过期关闭",
    "project.pinned": "常驻中",
    "project.running": "运行中",
    "project.stop": "停止",
    "project.keepAlive": "常驻",
    "common.choose": "选择",
    "expire.30m": "30 分钟",
    "expire.1h": "1 小时",
    "expire.2h": "2 小时（默认）",
    "expire.4h": "4 小时",
    "expire.never": "停用自动过期",
    "launch.detecting": "正在检测项目类型…",
    "launch.waitingServer": "已在后台启动，等待服务就绪…",
    "launch.opened": "（已打开）",
    "launch.noPortNotice": "已启动，但没有检测到新的网页 port（可能是原生 App、纯后端／数据库服务，本来就不会有网页；若还在等 Docker，可以到 Terminal 窗口确认进度，不需要重新拖入）",
    "launch.waitingElapsed": "正在等待 localhost…（已等待 %d 秒，随时可以到 Terminal 查看）",
    "launch.elapsedSuffix": "（已等待 %d 秒）",
    "autoclose.notice": "已自动关闭 localhost:%@（运行超过 %d 分钟）",
    "update.downloading": "正在下载更新…",
    "update.downloadFailed": "下载失败",
    "update.downloadFailedWithError": "更新下载失败：%@",
    "update.installing": "正在安装…",
    "update.mountFailed": "挂载更新文件失败",
    "update.appNotFoundInImage": "更新文件里找不到 mole.app",
    "update.replacing": "正在替换旧版本…",
    "update.copyFailed": "复制新版本失败：%@",
    "update.installFailed": "安装新版本失败（可能没有写入权限），请自行前往 Release 页面下载安装：%@",
    "update.restarting": "更新完成，重新启动中…",
    "update.updating": "正在更新…",
    "update.newVersionAvailable": "🎉 有新版本 v%@ 可下载",
    "update.now": "立即更新",
    "update.viewRelease": "前往查看",
    "loading.detecting": "正在识别项目…",
    "loading.preparing": "正在准备环境…",
    "loading.startingServer": "正在启动开发服务器…",
    "loading.waitingLocalhost": "正在等待 localhost…",
    "loading.openingBrowser": "正在打开浏览器…",
    "loading.ready": "项目已准备完成。",
    "error.projectNotFound": "找不到这个项目。",
    "error.folderInaccessible": "无法访问这个文件夹。",
    "error.portInUse": "这个 port 已经被占用了。",
    "error.commandFailed": "指令执行失败。",
    "error.unableToStartServer": "无法启动服务器。",
    "error.dependencyMissing": "缺少必要的依赖包。",
    "error.invalidProject": "这看起来不是一个有效的项目。",
    "error.permissionDenied": "权限不足。",
    "error.browserFailedToOpen": "无法打开浏览器。",
    "error.processStoppedUnexpectedly": "进程意外终止了。",
    "uptime.days": "已运行 %d 天 %d 小时",
    "uptime.hours": "已运行 %d 小时 %d 分",
    "uptime.minutes": "已运行 %d 分钟",
    "uptime.seconds": "已运行 %d 秒",
    "uptime.short.days": "%d 天",
    "uptime.short.hours": "%d 时",
    "uptime.short.minutes": "%d 分",
    "uptime.short.lessThanMinute": "< 1 分钟",
    "about.credit": "由 温 Wen 和 Claude 协同制作 ⌯^⦁𖥦⦁^⌯",
]
