import Foundation

// 日本語 (Japanese)
let stringsJA: [String: String] = [
    "tagline": "コマンドいらずで、すぐ作業へ",
    "drop.title": "プロジェクトフォルダをここにドロップ",
    "drop.subtitle": "コマンドを覚えなくても、あとはおまかせ",
    "drop.button": "フォルダを選択",
    "drop.doodle": "drag it!",
    "drop.hover.title": "drop it here",
    "drop.hover.subtitle": "受け取った！",
    "drop.hover.doodle": "gimme!",
    "drop.lastLaunched": "前回の起動：",
    "launch.title": "プロジェクトを解析中",
    "launch.subtitle": "このフォルダの中身をのぞいてみましょう",
    "launch.doodle": "digging⋯",
    "launch.cancel": "やめておく",
    "empty.title": "現在起動中のプロジェクトはありません",
    "empty.zzz": "zzz⋯",
    "autoclose.title": "自動終了",
    "autoclose.subtitle": "放置されたプロジェクトは自動的に終了します",
    "running.title": "起動中のプロジェクト",
    "running.killAll": "すべて停止",
    "running.refresh": "更新",
    "settings.title": "設定",
    "settings.general": "一般",
    "settings.about": "アプリについて",
    "settings.story": "ストーリー",
    "story.heading": "このアプリを作った理由",
    "story.p1": "私はプロの開発者ではありません。バイブコーディングを重ねるうちにプロジェクトがどんどん増え、起動コマンドを覚えられなくなり、どの localhost ポートが動いているのかも分からなくなっていました。",
    "story.p2": "それに、プロジェクトを再起動したいだけなのに、そのたびに AI に聞き直すのも嫌でした。",
    "story.p3": "だから mole を作りました。フォルダを入れるだけ、あとは全部おまかせです。",
    "story.closing": "コマンドいらずで、すぐ作業へ。",
    "settings.language": "言語",
    "settings.github": "GitHub で見る",
    "settings.license": "MIT ライセンス",
    "settings.reportIssue": "問題を報告",
    "alert.stop.confirm": "停止",
    "alert.cancel": "キャンセル",
    "alert.stopTitle": "localhost:%@ を停止しますか？",
    "alert.killAllTitle": "すべて停止しますか？",
    "alert.killAllMessage": "%d 個の開発サーバー（localhost:%@）を停止します。",
    "alert.killAllSkipped": "\n「常時起動」に設定された %d 個のサービスは停止されません。",
    "pin.tooltip": "常時起動：自動終了の対象になりません",
    "project.pinned": "常時起動中",
    "project.running": "起動中",
    "project.stop": "停止",
    "project.keepAlive": "常時起動",
    "common.choose": "選択",
    "expire.30m": "30 分",
    "expire.1h": "1 時間",
    "expire.2h": "2 時間（デフォルト）",
    "expire.4h": "4 時間",
    "expire.never": "自動終了しない",
    "launch.detecting": "プロジェクトの種類を検出中…",
    "launch.waitingServer": "バックグラウンドで起動しました。準備が整うのを待っています…",
    "launch.opened": "（開きました）",
    "launch.noPortNotice": "起動しましたが、新しい Web ポートが検出されませんでした（ネイティブアプリやバックエンド／データベースサービスなど、もともと Web ページがない場合は正常です。Docker の起動待ちの場合は、再度ドロップせずログで進捗を確認してください）",
    "launch.waitingElapsed": "localhost を待っています…（経過 %d 秒、いつでもログを確認できます）",
    "launch.elapsedSuffix": "（経過 %d 秒）",
    "autoclose.notice": "localhost:%@ を自動終了しました（%d 分以上起動していたため）",
    "update.downloading": "アップデートをダウンロード中…",
    "update.downloadFailed": "ダウンロードに失敗しました",
    "update.downloadFailedWithError": "アップデートのダウンロードに失敗しました：%@",
    "update.installing": "インストール中…",
    "update.mountFailed": "アップデートイメージのマウントに失敗しました",
    "update.appNotFoundInImage": "アップデートイメージ内に mole.app が見つかりません",
    "update.replacing": "旧バージョンを置き換えています…",
    "update.copyFailed": "新しいバージョンのコピーに失敗しました：%@",
    "update.installFailed": "新しいバージョンのインストールに失敗しました（権限の問題の可能性があります）。Release ページから手動でダウンロードしてください：%@",
    "update.restarting": "アップデート完了、再起動しています…",
    "update.updating": "更新中…",
    "update.newVersionAvailable": "🎉 新しいバージョン v%@ が利用可能です",
    "update.now": "今すぐ更新",
    "update.viewRelease": "リリースを見る",
    "loading.detecting": "プロジェクトを検出中…",
    "loading.preparing": "環境を準備中…",
    "loading.startingServer": "開発サーバーを起動中…",
    "loading.waitingLocalhost": "localhost を待っています…",
    "loading.openingBrowser": "ブラウザを開いています…",
    "loading.ready": "プロジェクトの準備ができました。",
    "error.projectNotFound": "プロジェクトが見つかりません。",
    "error.folderInaccessible": "このフォルダにアクセスできません。",
    "error.portInUse": "そのポートはすでに使用されています。",
    "error.commandFailed": "コマンドの実行に失敗しました。",
    "error.unableToStartServer": "サーバーを起動できませんでした。",
    "error.dependencyMissing": "必要な依存関係が見つかりません。",
    "error.invalidProject": "有効なプロジェクトではないようです。",
    "error.permissionDenied": "権限がありません。",
    "error.browserFailedToOpen": "ブラウザを開けませんでした。",
    "error.processStoppedUnexpectedly": "プロセスが予期せず停止しました。",
    "uptime.days": "%d 日 %d 時間 起動中",
    "uptime.hours": "%d 時間 %d 分 起動中",
    "uptime.minutes": "%d 分 起動中",
    "uptime.seconds": "%d 秒 起動中",
    "uptime.short.days": "%d日",
    "uptime.short.hours": "%d時間",
    "uptime.short.minutes": "%d分",
    "uptime.short.lessThanMinute": "< 1 分",
    "about.credit": "Wen と Claude が一緒に制作 ⌯^⦁𖥦⦁^⌯",
]
