import Foundation

// English — default language. This is the reference key set: every other
// Strings.*.swift file must contain exactly the same keys.
let stringsEN: [String: String] = [
    "tagline": "Skip the commands, get to work.",
    "drop.title": "Drop your project folder here",
    "drop.subtitle": "No commands to remember, I'll figure it out",
    "drop.button": "Choose Folder",
    "drop.doodle": "drag it!",
    "drop.hover.title": "drop it here",
    "drop.hover.subtitle": "Got it!",
    "drop.hover.doodle": "gimme!",
    "drop.lastLaunched": "Last launched: ",
    "launch.title": "Analyzing project",
    "launch.subtitle": "Let's see what's in this folder",
    "launch.doodle": "digging⋯",
    "launch.cancel": "Never mind",
    "empty.title": "Nothing running right now",
    "empty.zzz": "zzz⋯",
    "autoclose.title": "Auto Close",
    "autoclose.subtitle": "Idle projects will close automatically",
    "running.title": "Running Projects",
    "running.killAll": "Stop All",
    "running.refresh": "Refresh",
    "settings.title": "Settings",
    "settings.general": "General",
    "settings.about": "About",
    "settings.story": "Story",
    "story.heading": "Why I made this app",
    "story.p1": "I'm not a professional developer. After a lot of vibe coding, I ended up with more and more projects, couldn't remember the start commands, and kept losing track of which localhost ports were even running.",
    "story.p2": "And I didn't want to ask an AI all over again just to get a project running.",
    "story.p3": "So I made mole. Drop in the folder, and it takes care of the rest.",
    "story.closing": "Skip the commands, get to work.",
    "settings.language": "Language",
    "settings.github": "View on GitHub",
    "settings.license": "MIT License",
    "settings.reportIssue": "Report an Issue",
    "alert.stop.confirm": "Stop",
    "alert.cancel": "Cancel",
    "alert.stopTitle": "Stop localhost:%@?",
    "alert.killAllTitle": "Stop all?",
    "alert.killAllMessage": "This will stop %d dev server(s) (localhost:%@).",
    "alert.killAllSkipped": "\n%d pinned service(s) marked Keep Alive won't be stopped.",
    "pin.tooltip": "Keep Alive: won't be closed automatically",
    "project.pinned": "pinned",
    "project.running": "Running",
    "project.stop": "Stop",
    "project.keepAlive": "Keep Alive",
    "common.choose": "Choose",
    "expire.30m": "30 min",
    "expire.1h": "1 hour",
    "expire.2h": "2 hours (default)",
    "expire.4h": "4 hours",
    "expire.never": "Never",
    "launch.detecting": "Detecting project type…",
    "launch.waitingServer": "Launched in the background, waiting for it to come up…",
    "launch.opened": " (opened)",
    "launch.noPortNotice": "Launched, but no new web port was detected (it may be a native app or a backend/database service with no web page — that's expected. If it's still waiting on Docker, check the log instead of dragging it in again)",
    "launch.waitingElapsed": "Waiting for localhost… (%d sec so far, check the log anytime)",
    "launch.elapsedSuffix": " (%d sec so far)",
    "autoclose.notice": "Automatically closed localhost:%@ (running over %d minutes)",
    "update.downloading": "Downloading update…",
    "update.downloadFailed": "Download failed",
    "update.downloadFailedWithError": "Update download failed: %@",
    "update.installing": "Installing…",
    "update.mountFailed": "Failed to mount the update image",
    "update.appNotFoundInImage": "Couldn't find mole.app inside the update image",
    "update.replacing": "Replacing the old version…",
    "update.copyFailed": "Failed to copy the new version: %@",
    "update.installFailed": "Failed to install the new version (maybe a permissions issue) — download it manually from the Releases page: %@",
    "update.restarting": "Update complete, restarting…",
    "update.updating": "Updating…",
    "update.newVersionAvailable": "🎉 A new version (v%@) is available",
    "update.now": "Update Now",
    "update.viewRelease": "View Release",
    "loading.detecting": "Detecting project…",
    "loading.preparing": "Preparing environment…",
    "loading.startingServer": "Starting development server…",
    "loading.waitingLocalhost": "Waiting for localhost…",
    "loading.openingBrowser": "Opening browser…",
    "loading.ready": "Project is ready.",
    "error.projectNotFound": "Project not found.",
    "error.folderInaccessible": "Can't access this folder.",
    "error.portInUse": "That port is already in use.",
    "error.commandFailed": "The command failed to run.",
    "error.unableToStartServer": "Couldn't start the server.",
    "error.dependencyMissing": "A required dependency is missing.",
    "error.invalidProject": "This doesn't look like a valid project.",
    "error.permissionDenied": "Permission denied.",
    "error.browserFailedToOpen": "Couldn't open the browser.",
    "error.processStoppedUnexpectedly": "The process stopped unexpectedly.",
    "uptime.days": "Running %d day(s) %d hr",
    "uptime.hours": "Running %d hr %d min",
    "uptime.minutes": "Running %d min",
    "uptime.seconds": "Running %d sec",
    "uptime.short.days": "%dd",
    "uptime.short.hours": "%dh",
    "uptime.short.minutes": "%dm",
    "uptime.short.lessThanMinute": "< 1 min",
    "about.credit": "Made by Wen and Claude, together ⌯^⦁𖥦⦁^⌯",
]
