import Foundation

// 繁體中文 (Traditional Chinese)
let stringsZhTW: [String: String] = [
    "tagline": "別管指令，直接開工",
    "drop.title": "把專案資料夾拖到這裡",
    "drop.subtitle": "不用記指令，我來判斷",
    "drop.button": "選擇資料夾",
    "drop.doodle": "drag it!",
    "drop.hover.title": "drop it here",
    "drop.hover.subtitle": "我接住了！",
    "drop.hover.doodle": "gimme!",
    "drop.lastLaunched": "上次啟動：",
    "launch.title": "正在分析專案",
    "launch.subtitle": "看看這個資料夾裡藏了什麼",
    "launch.doodle": "digging⋯",
    "launch.cancel": "先不等了",
    "empty.title": "目前沒有專案在跑",
    "empty.zzz": "zzz⋯",
    "autoclose.title": "自動關閉",
    "autoclose.subtitle": "閒置專案將自動關閉",
    "running.title": "執行中的專案",
    "running.killAll": "全部關閉",
    "running.refresh": "重新整理",
    "settings.title": "設定",
    "settings.general": "一般",
    "settings.about": "關於",
    "settings.story": "故事",
    "story.heading": "為什麼做這個 App？",
    "story.p1": "我不是專業開發者。Vibe coding 做久了，專案越來越多，啟動指令記不住，連 localhost 開了哪些也常常搞不清楚。",
    "story.p2": "我又不想每次只是為了重新把專案跑起來，就再問一次 AI。",
    "story.p3": "所以做了 mole。把資料夾丟進來，剩下交給它。",
    "story.closing": "別管指令，直接開工。",
    "settings.language": "語言",
    "settings.github": "在 GitHub 上查看",
    "settings.license": "MIT 授權",
    "settings.reportIssue": "回報問題",
    "alert.stop.confirm": "關閉",
    "alert.cancel": "取消",
    "alert.stopTitle": "關閉 localhost:%@？",
    "alert.killAllTitle": "全部關閉？",
    "alert.killAllMessage": "會關閉 %d 個開發伺服器（localhost:%@)。",
    "alert.killAllSkipped": "\n有標記「常駐」的 %d 個服務不會被關閉。",
    "pin.tooltip": "常駐：不會被自動過期關閉",
    "project.pinned": "常駐中",
    "project.running": "執行中",
    "project.stop": "停止",
    "project.keepAlive": "常駐",
    "common.choose": "選擇",
    "expire.30m": "30 分鐘",
    "expire.1h": "1 小時",
    "expire.2h": "2 小時（預設）",
    "expire.4h": "4 小時",
    "expire.never": "停用自動過期",
    "launch.detecting": "正在偵測專案類型…",
    "launch.waitingServer": "已在背景啟動，等待服務就緒…",
    "launch.opened": "（已開啟）",
    "launch.noPortNotice": "已啟動，但沒有偵測到新的網頁 port（可能是原生 App、純後端／資料庫服務，本來就不會有網頁；若還在等 Docker，可以到 Terminal 視窗確認進度，不需要重新拖曳）",
    "launch.waitingElapsed": "正在等待 localhost…（已等待 %d 秒，隨時可以到 Terminal 查看）",
    "launch.elapsedSuffix": "（已等待 %d 秒）",
    "autoclose.notice": "已自動關閉 localhost:%@（運行超過 %d 分鐘）",
    "update.downloading": "正在下載更新…",
    "update.downloadFailed": "下載失敗",
    "update.downloadFailedWithError": "更新下載失敗：%@",
    "update.installing": "正在安裝…",
    "update.mountFailed": "掛載更新檔失敗",
    "update.appNotFoundInImage": "更新檔裡找不到 mole.app",
    "update.replacing": "正在替換舊版本…",
    "update.copyFailed": "複製新版本失敗：%@",
    "update.installFailed": "安裝新版本失敗（可能沒有寫入權限），請自己到 Release 頁面下載安裝：%@",
    "update.restarting": "更新完成，重新啟動中…",
    "update.updating": "正在更新…",
    "update.newVersionAvailable": "🎉 有新版本 v%@ 可下載",
    "update.now": "立即更新",
    "update.viewRelease": "前往查看",
    "loading.detecting": "正在辨識專案…",
    "loading.preparing": "正在準備環境…",
    "loading.startingServer": "正在啟動開發伺服器…",
    "loading.waitingLocalhost": "正在等待 localhost…",
    "loading.openingBrowser": "正在開啟瀏覽器…",
    "loading.ready": "專案已準備完成。",
    "error.projectNotFound": "找不到這個專案。",
    "error.folderInaccessible": "無法存取這個資料夾。",
    "error.portInUse": "這個 port 已經被使用了。",
    "error.commandFailed": "指令執行失敗。",
    "error.unableToStartServer": "無法啟動伺服器。",
    "error.dependencyMissing": "缺少必要的依賴套件。",
    "error.invalidProject": "這看起來不是一個有效的專案。",
    "error.permissionDenied": "權限不足。",
    "error.browserFailedToOpen": "無法開啟瀏覽器。",
    "error.processStoppedUnexpectedly": "程序意外中止了。",
    "uptime.days": "已運行 %d 天 %d 小時",
    "uptime.hours": "已運行 %d 小時 %d 分",
    "uptime.minutes": "已運行 %d 分鐘",
    "uptime.seconds": "已運行 %d 秒",
    "uptime.short.days": "%d 天",
    "uptime.short.hours": "%d 時",
    "uptime.short.minutes": "%d 分",
    "uptime.short.lessThanMinute": "< 1 分鐘",
    "about.credit": "由 溫 Wen 和 Claude 協同製作 ⌯^⦁𖥦⦁^⌯",
]
