import Foundation

// Español (neutral Spanish, no regional variants)
let stringsES: [String: String] = [
    "tagline": "Olvídate de los comandos, ponte a trabajar.",
    "drop.title": "Suelta tu carpeta de proyecto aquí",
    "drop.subtitle": "No necesitas recordar comandos, yo me encargo",
    "drop.button": "Elegir carpeta",
    "drop.doodle": "drag it!",
    "drop.hover.title": "drop it here",
    "drop.hover.subtitle": "¡Lo tengo!",
    "drop.hover.doodle": "gimme!",
    "drop.lastLaunched": "Último inicio: ",
    "launch.title": "Analizando el proyecto",
    "launch.subtitle": "Veamos qué hay en esta carpeta",
    "launch.doodle": "digging⋯",
    "launch.cancel": "Mejor no",
    "empty.title": "No hay nada corriendo ahora mismo",
    "empty.zzz": "zzz⋯",
    "autoclose.title": "Cierre automático",
    "autoclose.subtitle": "Los proyectos inactivos se cerrarán automáticamente",
    "running.title": "Proyectos en ejecución",
    "running.killAll": "Detener todo",
    "running.refresh": "Actualizar",
    "settings.title": "Ajustes",
    "settings.general": "General",
    "settings.about": "Acerca de",
    "settings.story": "Historia",
    "story.heading": "Por qué hice esta app",
    "story.p1": "No soy un desarrollador profesional. Después de mucho vibe coding, terminé con cada vez más proyectos, sin poder recordar los comandos de inicio, y sin saber muy bien qué puertos de localhost seguían activos.",
    "story.p2": "Y no quería tener que preguntarle a una IA otra vez solo para volver a levantar un proyecto.",
    "story.p3": "Así que hice mole. Sueltas la carpeta y él se encarga del resto.",
    "story.closing": "Olvídate de los comandos, ponte a trabajar.",
    "settings.language": "Idioma",
    "settings.github": "Ver en GitHub",
    "settings.license": "Licencia MIT",
    "settings.reportIssue": "Reportar un problema",
    "alert.stop.confirm": "Detener",
    "alert.cancel": "Cancelar",
    "alert.stopTitle": "¿Detener localhost:%@?",
    "alert.killAllTitle": "¿Detener todo?",
    "alert.killAllMessage": "Esto detendrá %d servidor(es) de desarrollo (localhost:%@).",
    "alert.killAllSkipped": "\n%d servicio(s) marcados como \"Mantener activo\" no se detendrán.",
    "pin.tooltip": "Mantener activo: no se cerrará automáticamente",
    "project.pinned": "fijado",
    "project.running": "Activo",
    "project.stop": "Detener",
    "project.keepAlive": "Mantener activo",
    "common.choose": "Elegir",
    "expire.30m": "30 min",
    "expire.1h": "1 hora",
    "expire.2h": "2 horas (predeterminado)",
    "expire.4h": "4 horas",
    "expire.never": "Nunca",
    "launch.detecting": "Detectando el tipo de proyecto…",
    "launch.waitingServer": "Iniciado en segundo plano, esperando a que esté listo…",
    "launch.opened": " (abierto)",
    "launch.noPortNotice": "Se inició, pero no se detectó ningún puerto web nuevo (puede ser una app nativa o un servicio backend/base de datos sin página web — eso es normal. Si todavía está esperando a Docker, revisa el registro en lugar de volver a soltar la carpeta)",
    "launch.waitingElapsed": "Esperando a localhost… (%d s transcurridos, puedes revisar el registro cuando quieras)",
    "launch.elapsedSuffix": " (%d s transcurridos)",
    "autoclose.notice": "Se cerró automáticamente localhost:%@ (llevaba más de %d minutos activo)",
    "update.downloading": "Descargando actualización…",
    "update.downloadFailed": "Error al descargar",
    "update.downloadFailedWithError": "Error al descargar la actualización: %@",
    "update.installing": "Instalando…",
    "update.mountFailed": "No se pudo montar la imagen de actualización",
    "update.appNotFoundInImage": "No se encontró mole.app dentro de la imagen de actualización",
    "update.replacing": "Reemplazando la versión anterior…",
    "update.copyFailed": "Error al copiar la nueva versión: %@",
    "update.installFailed": "Error al instalar la nueva versión (puede ser un problema de permisos) — descárgala manualmente desde la página de Releases: %@",
    "update.restarting": "Actualización completa, reiniciando…",
    "update.updating": "Actualizando…",
    "update.newVersionAvailable": "🎉 Hay una nueva versión (v%@) disponible",
    "update.now": "Actualizar ahora",
    "update.viewRelease": "Ver versión",
    "loading.detecting": "Detectando el proyecto…",
    "loading.preparing": "Preparando el entorno…",
    "loading.startingServer": "Iniciando el servidor de desarrollo…",
    "loading.waitingLocalhost": "Esperando a localhost…",
    "loading.openingBrowser": "Abriendo el navegador…",
    "loading.ready": "El proyecto está listo.",
    "error.projectNotFound": "No se encontró el proyecto.",
    "error.folderInaccessible": "No se puede acceder a esta carpeta.",
    "error.portInUse": "Ese puerto ya está en uso.",
    "error.commandFailed": "El comando falló al ejecutarse.",
    "error.unableToStartServer": "No se pudo iniciar el servidor.",
    "error.dependencyMissing": "Falta una dependencia necesaria.",
    "error.invalidProject": "Esto no parece ser un proyecto válido.",
    "error.permissionDenied": "Permiso denegado.",
    "error.browserFailedToOpen": "No se pudo abrir el navegador.",
    "error.processStoppedUnexpectedly": "El proceso se detuvo inesperadamente.",
    "uptime.days": "Activo hace %d día(s) %d h",
    "uptime.hours": "Activo hace %d h %d min",
    "uptime.minutes": "Activo hace %d min",
    "uptime.seconds": "Activo hace %d s",
    "uptime.short.days": "%dd",
    "uptime.short.hours": "%dh",
    "uptime.short.minutes": "%dmin",
    "uptime.short.lessThanMinute": "< 1 min",
    "about.credit": "Hecho por Wen y Claude, juntos ⌯^⦁𖥦⦁^⌯",
]
